apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - thoth-notification.yaml
images:
  - name: graph-backup-job
    newName: image-registry.openshift-image-registry.svc:5000/thoth-graph-stage/graph-backup-job
    newTag: latest
patchesStrategicMerge:
  - cronjob.yaml
  - imagestreamtag.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: "thoth-infra-stage"
    target:
      group: batch
      version: v1
      kind: Job
      annotationSelector: "operation=chat-notification"
  - patch: |-
      - op: replace
        path: "/spec/jobTemplate/spec/template/spec/containers/0/resources/requests/ephemeral-storage"
        value: "20Gi"
      - op: replace
        path: "/spec/jobTemplate/spec/template/spec/containers/0/resources/limits/ephemeral-storage"
        value: "20Gi"
    target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: graph-backup
